server:
  port: 8989

spring:
  datasource:
    # 动态切换数据源
    dynamic:
      # 默认库,默认master
      primary: master
      # 是否严格模式，默认false；严格模式下未匹配到数据源直接报错, 非严格模式下则使用默认数据源primary所设置的数据源
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://www.youlai.tech:3306/youlai_boot?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true
          username: youlai
          password: 123456
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://www.youlai.tech:3306/youlai_boot_slave?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true
          username: youlai
          password: 123456
  data:
    redis:
      database: 6
      host: www.youlai.tech
      port: 6379
      password: 123456
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

mybatis-plus:
  global-config:
    db-config:
      # 主键ID类型
      id-type: none
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 认证配置
auth:
  token:
    secret_key: SecretKey012345678901234567890123456789012345678901234567890123456789
    # token 有效期(单位:秒)
    ttl: 18000

# MinIO 分布式文件系统
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  # 存储桶名称
  bucket-name: default
  # 自定义域名(非必须)，Nginx配置反向代理转发文件路径
  custom-domain:

# springdoc配置： https://springdoc.org/properties.html
springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    tags-sorter: alpha
  api-docs:
    enabled: true

# 验证码配置
easycaptcha:
  enable: true
  type: arithmetic
  ttl: 120